export const actionTypes = {
  SET_USER_DATA: 'SET_USER_DATA',
  SET_LOADER: 'SET_LOADER',
  SET_TOAST: 'SET_TOAST',
  SET_SIGN_UP: 'SET_SIGN_UP',
  SET_SIGN_IN: 'SET_SIGN_IN',
  SET_LOGOUT: 'SET_LOGOUT',
  SET_RESPONSE: 'SET_RESPONSE',
  SET_AUTH_LOADER: 'SET_AUTH_LOADER',
  SET_GOOGLE_SIGNIN: 'SET_GOOGLE_SIGNIN',
  SET_FRIENDS: 'SET_FRIENDS',
  FRIENDS_LIST: 'Friend List',
  RECEIVE_FRIEND_REQUEST: 'RECEIVE_FRIEND_REQUEST',
  SET_SEARCH_FRIEND: 'SET_SEARCH_FRIEND',
  FRIEND_REQUEST: 'Friend Requests',
  SET_SENT_FRIEND_REQUEST: 'SET_SENT_FRIEND_REQUEST',
  SET_ACCEPT_FRIEND_REQUEST:'SET_ACCEPT_FRIEND_REQUEST',
  SET_FRIEND_REQUEST_LIST:'SET_FRIEND_REQUEST_LIST'
};
